### PR TITLE
Bugfix/long lists

### LINKED ISSUE #35: Error Thrown when Indexing Long Lists
When using `typeof` to enumerate a long list of consts to get a set of values, if the list is long enough, typescript will truncate the the values we use to convert to XLR and we get an error thrown. It seems like our [current approach](https://github.com/player-ui/tools/blob/bugfix/long-lists/xlr/converters/src/ts-to-xlr.ts#L468) of pulling that info from the `Type` object might need to be more robust. [This branch](https://github.com/player-ui/tools/tree/bugfix/long-lists) has a failing test that can be used to validate the new approach works. 

image

### PR DESCRIPTION
**Pull request by KetanReddy**
Closes #35 

## Release Notes
Fixes issues when long constant lists were indexed to create a union.

### CODE REVIEW

**Comment by KetanReddy** [comment]
The `1` in the `typeToTypeNode` call is a parameter to disable truncation 

image

File: xlr/converters/src/ts-to-xlr.ts [hunk 1]
```diff
@@ -469,7 +469,7 @@ export class TsConverter {
       const syntheticType = this.context.typeChecker.typeToTypeNode(
         effectiveType,
         node,
-        undefined
+        1
```
Comment (adierkens) [inline xlr/converters/src/ts-to-xlr.ts:472]: Can we use the enum here?

`NodeBuilderFlags.NoTruncation`

Comment (KetanReddy) [reply xlr/converters/src/ts-to-xlr.ts:472]: Ah, good call.
